import { useState } from 'react';
import { ArrowRight, BookOpen, Bot, CalendarDays, Camera, Check, ChevronDown, CircuitBoard, Clock3, Cpu, MapPin, Menu, MessageCircle, Printer, ShieldCheck, Sparkles, Users, Wrench, X, Zap } from 'lucide-react';
import './App.css';

const WA = '6283802436288';
const chat = (text = 'Halo IDN Maker Space, saya ingin tahu lebih lanjut tentang membership.') => `https://wa.me/${WA}?text=${encodeURIComponent(text)}`;

const tools = [
  { name: 'Electronics bench', detail: 'Solder digital, power supply, multimeter, dan toolkit presisi.', icon: CircuitBoard, image: '/images/electronics-iot-real.webp' },
  { name: '3D printing lab', detail: 'Bambu Lab A1 mini untuk prototipe cepat dan iterasi produk.', icon: Printer, image: '/images/tools/bambu-a1-mini.jpg' },
  { name: 'Embedded corner', detail: 'ESP32, sensor, dan alat ukur untuk proyek IoT yang nyata.', icon: Cpu, image: '/images/prototype-robotarm-real.webp' },
];
const paths = [
  ['01', 'IoT & Embedded Systems', '4–6 bulan', 'ESP32, MQTT, sensor integration, dan cloud-connected prototypes.', Cpu],
  ['02', 'PCB Design & Electronics', '3–5 bulan', 'KiCad, prototyping, soldering SMD, dan standar kerja elektronika.', CircuitBoard],
  ['03', 'Robotics', '6–9 bulan', 'ROS 2, motion planning, machine vision, dan robot bergerak.', Bot],
  ['04', 'Industrial Automation', '5–8 bulan', 'PLC, ladder logic, SCADA, dan otomasi yang relevan untuk industri.', Zap],
];
const plans = [
  { name: 'Drop-in', price: '25–35rb', period: '/ hari', desc: 'Untuk mencoba lab atau menyelesaikan satu proyek.', benefits: ['Akses lab sesuai jam buka', 'Penggunaan alat tersedia', 'Safety briefing singkat'] },
  { name: 'Basic', price: '150–200rb', period: '/ bulan', desc: 'Untuk mahasiswa yang ingin rutin belajar dan membangun.', benefits: ['Akses lab bulanan', 'Diskon workshop 10%', 'Komunitas member', 'Build night mingguan'] },
  { name: 'Pro', price: '300–400rb', period: '/ bulan', desc: 'Untuk maker serius yang membutuhkan prioritas dan ruang tumbuh.', benefits: ['Semua benefit Basic', 'Prioritas booking alat', 'Loker pribadi', 'Early access learning path'], featured: true },
];
const faqs = [
  ['Apakah harus punya pengalaman elektronika?', 'Tidak. Kami menyiapkan orientasi, safety briefing, dan jalur belajar dari level pemula.'],
  ['Apakah bisa datang tanpa menjadi member?', 'Bisa. Paket Drop-in cocok untuk kunjungan satu hari, selama kapasitas dan alat tersedia.'],
  ['Kapan IDN Maker Space buka?', 'Rencana jam operasional Senin–Sabtu 09.00–22.00 dan Minggu 10.00–18.00. Konfirmasi jadwal lewat WhatsApp.'],
  ['Bagaimana cara booking alat?', 'Pada tahap awal, booking dikonfirmasi langsung oleh admin melalui WhatsApp. Sistem booking terpadu disiapkan bertahap.'],
  ['Metode pembayaran apa yang tersedia?', 'Tahap awal menggunakan QRIS atau transfer yang dikonfirmasi admin. Integrasi Midtrans akan menyusul.'],
];

function Logo() {
  return <a className="brand" href="#top"><span className="brand-mark"><CircuitBoard size={22} /></span><span><b>IDN</b> Maker Space<small>Electronics lab · Lampung</small></span></a>;
}

export default function App() {
  const [menu, setMenu] = useState(false);
  const [faq, setFaq] = useState(0);
  const close = () => setMenu(false);
  return <div id="top">
    <header className="header"><div className="container nav"><Logo /><nav className={menu ? 'links open' : 'links'}><a href="#fasilitas" onClick={close}>Fasilitas</a><a href="#belajar" onClick={close}>Belajar</a><a href="#membership" onClick={close}>Membership</a><a href="#faq" onClick={close}>FAQ</a><a className="button dark small" href={chat()} target="_blank" rel="noreferrer">Gabung sekarang <ArrowRight size={16} /></a></nav><button className="menu" onClick={() => setMenu(!menu)} aria-label="Buka navigasi">{menu ? <X /> : <Menu />}</button></div></header>
    <main>
      <section className="hero section"><div className="container hero-grid"><div><p className="eyebrow"><Sparkles size={16} /> Electronics makerspace pertama di Lampung</p><h1>Belajar engineering dengan <em>membuat sesuatu.</em></h1><p className="lead">Akses alat industri, mentor, dan komunitas untuk mengubah teori kampus menjadi proyek yang bisa kamu tunjukkan.</p><div className="actions"><a className="button primary" href={chat('Halo IDN Maker Space, saya ingin menjadi founding member.')} target="_blank" rel="noreferrer">Gabung founding member <ArrowRight size={18} /></a><a className="button ghost" href="#fasilitas">Jelajahi fasilitas</a></div><div className="proof"><div className="avatars"><span>EL</span><span>IF</span><span>ME</span></div><p><b>Dibangun untuk engineer muda Lampung</b><br />Elektronika · IoT · Robotika · Fabrikasi</p></div></div><div className="hero-visual"><img src="/images/community-real.png" alt="Komunitas maker berkolaborasi" /><div className="float top"><i /> Lab access <b>09.00–22.00</b></div><div className="float bottom"><Wrench size={20} /><span><b>10+ alat</b><small>siap untuk berkarya</small></span></div></div></div></section>
      <section className="stats"><div className="container stats-grid"><div><b>25.794</b><span>mahasiswa ITERA</span></div><div><b>10+</b><span>peralatan maker</span></div><div><b>4</b><span>learning paths</span></div><div><b>1</b><span>ekosistem bersama</span></div></div></section>
      <section className="section problem"><div className="container"><div className="heading split"><div><p className="eyebrow">Dari teori ke karya nyata</p><h2>Lab bukan cuma ruangan.<br />Ia harus membuka peluang.</h2></div><p>Kami menjembatani keterbatasan akses alat, waktu praktik, dan mentorship agar mahasiswa bisa berkembang lebih cepat.</p></div><div className="compare"><article className="before"><small>Hari ini</small><h3>Belajar praktik masih terbatas</h3><ul><li><X /> Akses lab hanya beberapa jam</li><li><X /> Alat industri sulit dijangkau</li><li><X /> Proyek berjalan sendirian</li></ul></article><article className="after"><small>Bersama IDN</small><h3>Ide punya tempat untuk tumbuh</h3><ul><li><Check /> Jam akses lebih fleksibel</li><li><Check /> Equipment dan safety standard</li><li><Check /> Mentor serta komunitas aktif</li></ul></article></div></div></section>
      <section className="section facilities" id="fasilitas"><div className="container"><div className="heading"><p className="eyebrow">Fasilitas untuk membangun</p><h2>Dari rangkaian pertama<br />hingga prototipe siap uji.</h2><p>Mulai dengan alat yang tepat, lingkungan aman, dan bantuan saat kamu membutuhkannya.</p></div><div className="tool-grid">{tools.map((item) => { const Icon = item.icon; return <article className="tool" key={item.name}><div className="tool-img"><img src={item.image} alt={item.name} /><span><Icon size={18} /></span></div><div className="tool-copy"><small>Workshop zone</small><h3>{item.name}</h3><p>{item.detail}</p><a href={chat(`Halo IDN Maker Space, saya ingin tanya tentang ${item.name}.`)} target="_blank" rel="noreferrer">Tanya ketersediaan <ArrowRight size={15} /></a></div></article>; })}</div><div className="safety"><ShieldCheck /><span><b>Safety first, always.</b> Setiap member mengikuti orientasi lab dan briefing alat sebelum mulai.</span></div></div></section>
      <section className="section learning" id="belajar"><div className="container learning-grid"><div className="learning-intro"><p className="eyebrow light">Belajar dengan arah</p><h2>Empat jalur.<br />Satu portofolio yang berbicara.</h2><p>Fondasi, praktik terarah, dan proyek akhir yang relevan dengan kebutuhan industri.</p><a className="button light" href={chat('Halo IDN Maker Space, saya ingin masuk daftar tunggu learning path.')} target="_blank" rel="noreferrer">Masuk daftar tunggu <ArrowRight size={18} /></a></div><div className="path-list">{paths.map(([n, title, duration, desc, Icon]) => <article key={title}><span>{n}</span><i><Icon /></i><div><h3>{title}</h3><p>{desc}</p><small><Clock3 size={14} /> {duration} · Pemula sampai lanjut</small></div></article>)}</div></div></section>
      <section className="section community"><div className="container community-grid"><div className="community-img"><img src="/images/prototype-robotarm-real.jpg" alt="Prototipe lengan robot karya maker" /><span>Build · Test · Share</span></div><div className="community-copy"><p className="eyebrow">Komunitas yang ikut membangun</p><h2>Datang dengan rasa ingin tahu. Pulang dengan karya.</h2><p>Build Night mingguan, workshop tematik, peer review, dan mentor pairing membuat proses belajar tidak berhenti di tutorial.</p><div className="points"><div><Users /><span><b>Build together</b><small>Temukan rekan satu proyek.</small></span></div><div><BookOpen /><span><b>Learn by doing</b><small>Materi singkat, praktik lebih banyak.</small></span></div><div><CalendarDays /><span><b>Show up weekly</b><small>Ritme konsisten untuk maju.</small></span></div></div></div></div></section>
      <section className="section membership" id="membership"><div className="container"><div className="heading center"><p className="eyebrow">Pilih cara kamu mulai</p><h2>Akses lab yang masuk akal<br />untuk setiap tahap.</h2><p>Harga rentang mengikuti rencana BRD dan akan dikonfirmasi sebelum pembayaran.</p></div><div className="prices">{plans.map((p) => <article className={p.featured ? 'price featured' : 'price'} key={p.name}>{p.featured && <span className="badge">Paling populer</span>}<h3>{p.name}</h3><p>{p.desc}</p><div className="amount"><b>Rp {p.price}</b><span>{p.period}</span></div><ul>{p.benefits.map((x) => <li key={x}><Check /> {x}</li>)}</ul><a className={p.featured ? 'button primary full' : 'button ghost full'} href={chat(`Halo IDN Maker Space, saya tertarik paket ${p.name}.`)} target="_blank" rel="noreferrer">Pilih {p.name} <ArrowRight size={16} /></a></article>)}</div></div></section>
      <section className="section" id="faq"><div className="container faq-grid"><div><p className="eyebrow">Pertanyaan umum</p><h2>Sebelum kamu datang.</h2><p>Belum menemukan jawaban? Admin kami siap membantu lewat WhatsApp.</p><a className="text-link" href={chat()} target="_blank" rel="noreferrer"><MessageCircle /> Chat dengan admin</a></div><div>{faqs.map(([q, a], i) => <article className={faq === i ? 'faq open' : 'faq'} key={q}><button onClick={() => setFaq(faq === i ? -1 : i)}><span>{q}</span><ChevronDown /></button><div><p>{a}</p></div></article>)}</div></div></section>
      <section className="final"><div className="container cta"><div><p className="eyebrow light">Founding member intake</p><h2>Bangun skill.<br />Bangun proyek.<br />Bangun ekosistemnya.</h2></div><div><p>Jadilah bagian dari kelompok pertama yang ikut membentuk budaya maker di Lampung.</p><a className="button light" href={chat('Halo IDN Maker Space, saya ingin mendaftar sebagai founding member.')} target="_blank" rel="noreferrer">Mulai lewat WhatsApp <ArrowRight /></a></div></div></section>
    </main>
    <footer><div className="container footer-grid"><div><Logo /><p>Makerspace elektronika untuk engineer muda Lampung belajar, berkolaborasi, dan menciptakan.</p></div><div><b>Eksplorasi</b><a href="#fasilitas">Fasilitas</a><a href="#belajar">Learning path</a><a href="#membership">Membership</a></div><div><b>Kunjungi</b><span><MapPin /> Area ITERA, Lampung Selatan</span><span><Clock3 /> Sen–Sab, 09.00–22.00</span></div><div><b>Terhubung</b><a href="https://www.instagram.com/idnmakerspace" target="_blank" rel="noreferrer"><Camera /> Instagram</a><a href={chat()} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp</a></div></div><div className="container footnote"><span>© 2026 IDN Maker Space</span><span>Built in Lampung for Indonesia.</span></div></footer>
  </div>;
}
